### ISSUE TITLE
Proposal: Improve token create / update 

### ISSUE THREAD

**Issue by GM-Alex** [metaplex-foundation/js#317] opened 2022-09-28 13:17 UTC
As far as I understand the metaplex.nfts().create() function can be also used to create SFT and SPL tokens with metadata. The functions under NFTs could stay there but with a reduced arguments set. Ideally imho it should be like so:

- metaplex.tokens().create() is able to create a SPL token, a SFT or a NFT
- metaplex.spl().create() uses metaplex.tokens().create() but with the arguments preset to be only able to create a SFT
- metaplex.nfts().create() uses metaplex.tokens().create() but with the arguments preset to be only able to create a NFT

Same should be also done for all other functions related to this. That is much less confusing and makes the api much more intuitive.

**Comment by lorisleiva** [comment] 2022-09-30 11:23
Hi there 👋 

Thanks for taking the time to provide this feedback.

> metaplex.spl().create()

I'm assuming you made a typo here and you meant `metaplex.sfts().create()` since SPL stands for Solana Program Library.

My issue with the proposed approach is that both NFTs and SFTs, in the context of Metaplex, have an associated Metadata account. If you wish to create tokens without any Metadata account, then you may use the Token module accessible via `metaplex.tokens()`.

That being said, I agree that having NFTs and SFTs under `metaplex.nfts()` is a bit confusing. An alternative would be to rename this module `metaplex.tokenMetadata()` to be explicit or `metaplex.digitalAssets()` to comply with the latest language on the standard.

Does that make sense?

**Comment by GM-Alex** [comment] 2022-09-30 20:47
Hi @lorisleiva,

you are totally right I made a typo. 

Since, as far as I understand, NFTs and SFTs are a subset of tokens, my idea is to enhance the tokens module in the way that it can create any token with the create command. But since you mentioned that there are tokens without metadata, maybe the module should become a command called `createWithMetadata`. This would make it also easy to create tokens like for example white list tokens for the candy machine, which also could have metadata.

If the tokens module is then able to create any sort of tokens the nft module could still remain its create method but it uses the new `createWithMetadata` with preset arguments which shouldn't be able to change, like for example the decimals equals to zero, which makes the creation of NFTs less faulty. For special cases you still have the new `createWithMetadata` method. Same goes for the SFTs.

What do you think?

**Comment by lorisleiva** [comment] 2022-11-23 15:54
Hi there, sorry for the late reply. I think what you're saying makes sense and I'm likely going to change the structure of that module in the future but most people would prefer a high abstraction when creating SFTs and NFTs than using a token module and adding metadata to it.

IMO it mostly comes down to finding a better name for the NFT module as it encapsulates both NFTs and SFTs. Something like `metaplex.digitalAssets().createNft()` might be a better design.

I'll close this for now since it's not a bug on the SDK but I do appreciate your input on the SDK's API. Thank you!

**Closed by lorisleiva** 2022-11-23 15:54 UTC
Labels: question
