### ISSUE TITLE
npm installation fails due to husky

### ISSUE THREAD

**Issue by verata-veritatis** [metaplex-foundation/js#137] opened 2022-01-07 04:15 UTC
Attempting to install with `npm i @metaplex/js` fails with `4.11.1`:

```
npm ERR! code 1
npm ERR! path /Users/...
npm ERR! command failed
npm ERR! command sh -c husky install
npm ERR! .git can't be found (see https://git.io/Jc3F9)

npm ERR! A complete log of this run can be found in:
...
```

There are several issues open about this problem with `husky`. None of the solutions worked. I was able to install `@metaplex/js` without any issue when installing the previous version with `npm i @metaplex/js@4.10.1`. Some change was made in the latest version that broke the installation of `husky`.

**Comment by aheckmann** [comment] 2022-01-07 04:57
duplicate of #135. closing

**Comment by aheckmann** [comment] 2022-01-07 04:58
still working on getting the updated release out. CI failure

**Closed by aheckmann** 2022-01-07 04:57 UTC
Labels: SDK: JS
