### ISSUE TITLE
uploadMetadata(...) fails: MetaplexError: Bundlr > Failed to Initialize Bundlr

### ISSUE THREAD

**Issue by zkhalapyan** [metaplex-foundation/js#85] opened 2022-05-01 22:32 UTC
See code below; fails at `uploadMetadata(...)` 

```JS
const {
  Metaplex,
  keypairIdentity,
  bundlrStorage,
} = require("@metaplex-foundation/js-next");

async function mint(keypair: Keypair) {
  if (!keypair) {
    return;
  }
  const metaplex = Metaplex.make(connection)
    .use(keypairIdentity(keypair))
    .use(bundlrStorage());

  const { uri } = await metaplex.nfts().uploadMetadata({
    name: "My NFT",
    description: "My description",
    image:
      "https://www.arweave.net/VsKHsd9aJa2IZ82aYpcBuoT2PmXLifuM4HeeSYtRJj8?ext=jpeg",
  });

  console.log(uri);
```

Crash logs:

```
Unhandled Runtime Error
MetaplexError: Bundlr > Failed to Initialize Bundlr
>> Source: Plugin > Bundlr
>> Problem: Bundlr could not be initialized.
>> Solution: This could happen for a variety of reasons. Check the underlying error below for more information.

Caused By: TypeError: Cannot read properties of undefined (reading 'toBuffer')
```

<img width="976" alt="Screen Shot 2022-05-01 at 3 32 29 PM" src="https://user-images.githubusercontent.com/796815/166167166-8dc36ba6-2fab-4ee3-b94a-c4c43d71fdcb.png">

**Comment by lorisleiva** [comment] 2022-05-02 10:58
Hi 👋 

Could you please provide the steps to reproduce this error?

**Comment by zkhalapyan** [comment] 2022-05-03 18:05
@lorisleiva is the code above not enough? I am running it inside next.js. If you copy/paste this, it should repro.

**Comment by lorisleiva** [comment] 2022-05-03 21:06
I'm afraid not. I need to know how the SDK is being bundled and which build ends up being used by the application. If you can just let me know the exact steps to replicate the issue via a brand new next.js app, that'd be super helpful.

**Comment by zkhalapyan** [comment] 2022-05-05 19:16
Thanks for getting back — If you do a clean next-js install with TypeScript support, then run npm install on js-next, and run the code above, it will repro. If it helps, here are my packages/setup:

```
// package.json
{
  "name": "flex",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@metaplex-foundation/js-next": "^0.7.2",
    "@metaplex-foundation/mpl-token-metadata": "^2.1.1",
    "@solana/spl-token": "^0.2.0",
    "@solana/web3.js": "^1.41.1",
    "firebase": "^9.6.11",
    "js-next": "^1.0.0",
    "next": "12.1.5",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-google-button": "^0.7.2"
  },
  "devDependencies": {
    "@types/node": "17.0.29",
    "@types/react": "18.0.8",
    "@types/react-dom": "18.0.0",
    "autoprefixer": "^10.4.5",
    "eslint": "8.14.0",
    "eslint-config-next": "12.1.5",
    "postcss": "^8.4.12",
    "tailwindcss": "^3.0.24",
    "typescript": "4.6.3"
  }
}
```

```
// tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

```
// next.config.js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

module.exports = nextConfig
```

**Comment by zkhalapyan** [comment] 2022-05-06 19:30
Yeh, that could very much be the reason. I am using `require()` because of the issue I reported here, https://github.com/metaplex-foundation/js-next/issues/84. I guess we could try to fix that first and I can try to test this out.

**Comment by lorisleiva** [comment] 2022-05-10 08:11
Hey guys, still working on a fix for this. Bear with me. 😊

**Comment by lorisleiva** [comment] 2022-05-10 08:46
Could you try the new version `0.8.2` with NextJs whilst using `import` statements only and let me know if that works for you?

**Comment by StephanGerbeth** [comment] 2022-05-29 10:37
In version 0.9.0 it only works with require calls. If i use mjs with imports, i will get this error

````
@metaplex-foundation/js-next/dist/esm/plugins/bundlrStorage/BundlrStorageDriver.mjs:160
    const bundlr = identity instanceof KeypairIdentityDriver ? new BundlrPackage.default(address, currency, identity.keypair.secretKey, options) : new BundlrPackage.WebBundlr(address, currency, identity, options);
                                                               ^

TypeError: BundlrPackage.default is not a constructor
````

**Comment by lorisleiva** [comment] 2022-06-17 10:39
Hi there 👋 

Sorry for the late reply, it's been a busy month.

A lot of changes have been made to the SDK since version `0.9`.

Could anyone please tell me if they have the same issue with the SDK using the latest version `0.11.5`? 🙏

**Comment by MNaguib2611** [comment] 2022-06-17 14:22
Hello Loris ,
Thank you for your continuous support 
I am having an issue  with the same method
`const metaplex = Metaplex.make(connection)
    .use(keypairIdentity(keypair))
    .use(bundlrStorage());`
    
    I was using "@metaplex-foundation/js": "^0.11.1", and I have just switched to "@metaplex-foundation/js": "^0.11.5", but the same error 
    
    `Uncaught (in promise) TypeError: _bundlr_network_client__WEBPACK_IMPORTED_MODULE_0__ is not a constructor
    at BundlrStorageDriver.initNodeBundlr (BundlrStorageDriver.ts:195:1)
    at BundlrStorageDriver.initBundlr (BundlrStorageDriver.ts:175:1)
    at BundlrStorageDriver.bundlr (BundlrStorageDriver.ts:162:1)
    at BundlrStorageDriver.uploadAll (BundlrStorageDriver.ts:84:1)
    at StorageClient.uploadAll (StorageClient.ts:45:1)
    at Object.handle (uploadMetadata.ts:33:1)
    at Task.callback (OperationClient.ts:66:1)
    at Task.ts:82:1
    at Disposable.run (Disposable.ts:34:1)
    at Task.forceRun (Task.ts:74:1)`

**Closed** 2022-06-24 10:25 UTC

**Comment by lorisleiva** [comment] 2022-06-24 10:43
Hi all 👋 I was finally able to reproduce and fix this bug. I've even written a regression test for both ESM and CJS exports to make sure this doesn't happen again. Please upgrade to the latest version `0.11.7` and let me know if that fixes it for you.
