### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by PhongVu07** [metaplex-foundation/js#296] opened 2022-09-19 19:07 UTC
I'm using nextjs 12, after installing @metaplex-foundation/js v0.15.0 by app breaks with error `TypeError: Cannot read properties of undefined (reading 'prototype')`

**Comment by lorisleiva** [comment] 2022-09-20 08:47
Hi there 👋  

Not sure why this is the case. We have a [working example with Next.js 12](https://github.com/metaplex-foundation/js-examples/tree/main/getting-started-nextjs). 🤔 

Did Next.js change something on their latest version and no longer polyfills Node dependencies?

**Comment by lorisleiva** [comment] 2022-09-30 13:49
Hi again 👋 

I've had a look at the Next.js example again and couldn't reproduce this error I'm afraid.

I'm going to close this since we could not reproduce but if you're still getting the same error, please feel free to open a new issue using the latest version and, ideally, providing a public repository containing the minimum code required to replicate this issue. 

Thank you for your understanding.

**Closed by lorisleiva** 2022-09-30 13:49 UTC
Labels: question
