### ISSUE TITLE
MetaplexError: createNFT > NotEnoughAccountKeys

### ISSUE THREAD

**Issue by bounce-yukkw** [metaplex-foundation/js#305] opened 2022-09-23 04:06 UTC
i cant create NFT using metaplex foundation js v0.15.0 in mainet-beta, testnet 

anyone have a good idea?

 key: 'metaplex.errors.program.unknown_program_error',
  title: 'TokenMetadataProgram > Unknown Program Error',
  problem: 'The program [TokenMetadataProgram] at address [metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s] raised an error that is not recognized by the programs registered by the SDK.',
  solution: 'Unfortunately, you will need to check the unparsed error below to investigate what went wrong. To get more helpful error messages, ensure the program that failed is registered by the SDK and provides an "errorResolver" method.',
  source: 'program',
  sourceDetails: 'TokenMetadataProgram [metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s]',
  cause: SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 4: insufficient account keys for instruction
      at Connection.sendEncodedTransaction (/Users/user/Documents/hardhat-ts/node_modules/@solana/web3.js/src/connection.ts:4934:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Connection.sendRawTransaction (/Users/user/Documents/hardhat-ts/node_modules/@solana/web3.js/src/connection.ts:4893:20)
      at async RpcClient.sendTransaction (/Users/user/Documents/hardhat-ts/node_modules/@metaplex-foundation/js/src/plugins/rpcModule/RpcClient.ts:82:14)
      at async RpcClient.sendAndConfirmTransaction (/Users/user/Documents/hardhat-ts/node_modules/@metaplex-foundation/js/src/plugins/rpcModule/RpcClient.ts:117:23)
      at async TransactionBuilder.sendAndConfirm (/Users/user/Documents/hardhat-ts/node_modules/@metaplex-foundation/js/src/utils/TransactionBuilder.ts:189:22)
      at async Object.handle (/Users/user/Documents/hardhat-ts/node_modules/@metaplex-foundation/js/src/plugins/nftModule/operations/createNft.ts:132:20)
      at async /Users/user/Documents/hardhat-ts/node_modules/@metaplex-foundation/js/src/utils/Task.ts:82:23
      at async Disposable.run (/Users/user/Documents/hardhat-ts/node_modules/@metaplex-foundation/js/src/utils/Disposable.ts:34:14)
      at async /Users/user/Documents/hardhat-ts/scripts/create-item-nft.ts:69:23 {
    logs: [
      'Program 11111111111111111111111111111111 invoke [1]',
      'Program 11111111111111111111111111111111 success',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]',
      'Program log: Instruction: InitializeMint',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2967 of 1200000 compute units',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
      'Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]',
      'Program log: Create',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]',
      'Program log: Instruction: GetAccountDataSize',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1622 of 1191523 compute units',
      'Program return: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA pQAAAAAAAAA=',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
      'Program 11111111111111111111111111111111 invoke [2]',
      'Program 11111111111111111111111111111111 success',
      'Program log: Initialize the associated token account',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]',
      'Program log: Instruction: InitializeImmutableOwner',
      'Program log: Please upgrade to SPL Token 2022 for immutable owner support',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1405 of 1185033 compute units',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]',
      'Program log: Instruction: InitializeAccount3',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4241 of 1181153 compute units',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
      'Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 20438 of 1197033 compute units',
      'Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]',
      'Program log: Instruction: MintTo',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4536 of 1176595 compute units',
      'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
      'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]',
      'Program log: Instruction: Create Metadata Accounts v3',
      'Program log: Error: NotEnoughAccountKeys',
      'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 3633 of 1172059 compute units',
      'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: insufficient account keys for instruction'
    ]
  },
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Program 11111111111111111111111111111111 success',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]',
    'Program log: Instruction: InitializeMint',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2967 of 1200000 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]',
    'Program log: Create',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]',
    'Program log: Instruction: GetAccountDataSize',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1622 of 1191523 compute units',
    'Program return: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA pQAAAAAAAAA=',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Initialize the associated token account',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]',
    'Program log: Instruction: InitializeImmutableOwner',
    'Program log: Please upgrade to SPL Token 2022 for immutable owner support',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1405 of 1185033 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]',
    'Program log: Instruction: InitializeAccount3',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4241 of 1181153 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 20438 of 1197033 compute units',
    'Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]',
    'Program log: Instruction: MintTo',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4536 of 1176595 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]',
    'Program log: Instruction: Create Metadata Accounts v3',
    'Program log: Error: NotEnoughAccountKeys',
    'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 3633 of 1172059 compute units',
    'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: insufficient account keys for instruction'
  ],
  program: {
    name: 'TokenMetadataProgram',
    address: PublicKey {
      _bn: <BN: b7065b1e3d17c45389d527f6b04c3cd58b86c731aa0fdb549b6d1bc03f82946>
    },
    errorResolver: [Function: errorResolver],
    gpaResolver: [Function: gpaResolver]
  }
}

**Comment by AaronJaramillo** [comment] 2022-09-23 16:43
You may need to downgrade to mpl-token-metadata 2.2.4 until the new program version 1.4 is deployed to mainnet. 

`npm install @metaplex-foundation/mpl-token-metadata@2.2.4 --save`

see: [This issue response](https://github.com/metaplex-foundation/metaplex-program-library/issues/755#issuecomment-1253986047)

**Comment by CoachChuckFF** [comment] 2022-09-26 20:56
> You may need to downgrade to mpl-token-metadata 2.2.4 until the new program version 1.4 is deployed to mainnet.
> 
> `npm install @metaplex-foundation/mpl-token-metadata@2.2.4 --save`
> 
> see: [This issue response](https://github.com/metaplex-foundation/metaplex-program-library/issues/755#issuecomment-1253986047)

For anyone wanting the workaround to this problem: I can confirm the following works:

see: [This issue response](https://github.com/metaplex-foundation/js/issues/303#issuecomment-1256826597)

**Comment by lorisleiva** [comment] 2022-09-30 13:19
Hi there 👋 

I'll close this and mark as duplicate since it's already been raised in #303. 

Thanks @ninnjak for suggesting a temporary solution.

**Closed by lorisleiva** 2022-09-30 13:19 UTC
